version: '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080 #port hosta:port kontejnera
  authenticationDBProject:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
  redis:
    image: redis
    ports:
      - 6379:6379
  storeDBProject:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306